### ISSUE TITLE
Where does the DCAT need to be updated/made

### ISSUE THREAD

**Issue by simon-vc** [oSoc15/ipt-dcat#25]
Entry points for the DCAT feed?

**Comment by peterdesmet** [comment]
DCAT should be **generated on the fly** at the endpoint, just like the [RSS](http://data.inbo.be/ipt/rss.do) and the [inventory](http://data.inbo.be/ipt/inventory/dataset), and not updated with publication triggers. The reason is that the IPT might be installed with resources which will not trigger updates of DCAT. Generating on the fly is more robust.

I'm not sure what the URL of the endpoint should be: http://data.inbo.be/ipt/dcat ?

**Comment by peterdesmet** [comment]
Decided on http://data.inbo.be/ipt/dcat. Assigning issue to @simon-vc
