### ISSUE TITLE
Mapping Dataset dct:identifier

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#33]
We'll add `dct:identifier` to the dataset, which ideally is populated with the DOI of the dataset and if not available the GBIF registry key.
## 2 questions for @timrobertson100
1. Is the IPT aware of the DOI assigned by GBIF or only of DOIs assigned via the IPT?
2. What format do we choose for the identifier: URL or none URL?
   
   ```
   http://doi.org/10.15468/02omly
   doi:10.15468/02omly
   http://www.gbif.org/dataset/83e20573-f7dd-4852-9159-21566e1e691e
   83e20573-f7dd-4852-9159-21566e1e691e
   ```

**Comment by timrobertson100** [comment]
1. No, only IPT ones, but a [simple API call](http://api.gbif.org/v1/dataset/83e20573-f7dd-4852-9159-21566e1e691e) would get you it 
2. That depends...

Firstly, if you use a DOI I'd suggest storing in this format doi:10.15468/02omly but present it in whatever is most appropriate (e.g. in HTML, then make it a link because you want people to follow it).
If you are using the GBIF key, then I'd store internally just the UUID but present it as you see fit

Remember that the UUID will not change for the entity (ever) but it is feasible the DOI might do...

**Comment by peterdesmet** [comment]
For simplicity, I'd argue that at this stage we populate it with the GBIF stable URI: http://www.gbif.org/dataset/83e20573-f7dd-4852-9159-21566e1e691e

**Comment by peterdesmet** [comment]
@simon-vc: no DOIs, will just use keys (similar to organization keys)
