### ISSUE TITLE
What URI should we use for Publisher?

### ISSUE THREAD

**Issue by peterdesmet** [oSoc15/ipt-dcat#5]
The Publisher of a Catalog/Dataset is a resource, so it needs a URI. What URI should we use? There is no page/URI for this in the IPT (unlike Catalog, Dataset and Distribution), but there is at GBIF (e.g. http://www.gbif.org/publisher/1cd669d0-80ea-11de-a9d0-f1765f95f18b). That URI would not only work for INBO, but for all organizations using the IPT for GBIF. It does land on a HTML representation of the publisher though. Any ideas?

**Comment by pietercolpaert** [comment]
http://www.gbif.org/publisher/1cd669d0-80ea-11de-a9d0-f1765f95f18b identifies **a page** with more explanation about INBO, it doesn't identify the thing called INBO (although you could cheat a bit and still use this identifier... It would be only perceived as a minor issue by linked data people). Since we cannot change something on http://gbif.org (right?), I would choose a different identifier.

I'm not acquainted with how INBO is organised exactly, but does "EV INBO" identify who you are? Then this is a good identifier: https://opencorporates.com/id/companies/be/0898934731

If not, then you could also cheat for now and give it a URI that's not yet dereferenceable. E.g., http://www.inbo.be/#org

It might also be a perfect question to agentschap informatie vlaanderen to see what URIs you're going to use within the Flemish government for each department and gov service

**Comment by peterdesmet** [comment]
1. Just curious, https://opencorporates.com/id/companies/be/0898934731 is a good identifier because the information about that entity can also be retrieved as rdf from that site?
2. EV INBO is related to INBO (I'm an employee of EV INBO actually), but it's not the same as INBO, which is the actual publisher of our datasets.
3. The nice thing about using http://www.gbif.org/publisher/1cd669d0-80ea-11de-a9d0-f1765f95f18b is that it works for any organization using IPT, not just INBO. I'll touch base with GBIF regarding this.
4. Another solution would to have the user set a URI for their organization when they register their IPT. That way all IPT users can do this, but they're free to choose the URI.

**Comment by timrobertson100** [comment]
If I understand correctly, you want URLs like `inbo.be/ipt/resource?r=…#Dataset`

You could easily implement something to have `inbo.be/ipt/resource?r=…#Publisher` (or similar) by making the IPT do a call to the GBIF API such as `http://api.gbif.org/v1/organization/1cd669d0-80ea-11de-a9d0-f1765f95f18b` and then rewriting the JSON into whatever flavour you like.  

This way you could aim to have consistent URIs:

```
  inbo.be/ipt/resource/MAMM#Dataset
  inbo.be/ipt/resource/MAMM#Distribution
  inbo.be/ipt/publisher/1cd669d0-80ea-11de-a9d0-f1765f95f18b#Publisher
```

**Comment by peterdesmet** [comment]
Tim, is `inbo.be/ipt/resource/MAMM` a shorthand for `inbo.be/ipt/resource?r=MAMM` in your example, or are you suggesting that URLs like `inbo.be/ipt/resource/MAMM` are possible?

**Comment by timrobertson100** [comment]
Shorthand - but something you might want to incorporate as well in the changes

**Comment by pietercolpaert** [comment]
### Reply to https://github.com/LifeWatchINBO/ipt-dcat/issues/5#issuecomment-106348847

#### 1. Why the opencorporates URI is good

Yes it redirects to a representation depending on the Accept header of your request. E.g.,

``` bash
pieter@pieter-werk:~$ curl -H "Accept: application/rdf+xml" https://opencorporates.com/id/companies/be/0898934731 -i
HTTP/1.1 303 See Other
Content-Type: text/html
Content-Length: 120
Status: 303 See Other
Strict-Transport-Security: max-age=31536000
Location: https://opencorporates.com/companies/be/0898934731.rdf
```

#### 3. If we want to use the identifiers from GBIF because hten it works for all of GBIF

That's a very good point. The most pragmatic way, I believe, is asking @timrobertson100 to implement one of the following 2 options then. 

_The reason: we want a URI (an identifier, not a URL) for the organization itself, not for the JSON or the HTML document that says something about the organization. When we use the URI in HTTP requests, we should however get useful data (one of the linked data principles)_

##### Option 1: content negotiation

Give the HTML representation behind  http://www.gbif.org/publisher/1cd669d0-80ea-11de-a9d0-f1765f95f18b a different URI. E.g.,  http://www.gbif.org/publisher/1cd669d0-80ea-11de-a9d0-f1765f95f18b.html

When requesting the URI  http://www.gbif.org/publisher/1cd669d0-80ea-11de-a9d0-f1765f95f18b, a HTTP 303 See Other is given to the HTML page if the HTTP content negotiation wants HTML (as in the open corporates example). Furthermore, a RDF/XML or text/turtle representation can be implemented next to the HTML document.

##### Option 2: adding a hash to the URI

 http://www.gbif.org/publisher/1cd669d0-80ea-11de-a9d0-f1765f95f18b#Organization

If we follow this link, automatically the document at  http://www.gbif.org/publisher/1cd669d0-80ea-11de-a9d0-f1765f95f18b will be given. In this document, we can add RDF using RDFa: http://rdfa.info/

**Comment by peterdesmet** [comment]
Discussed this with @coreation. We'll use the GBIF publisher URL as the URI and include this in our DCAT document:

```
<catalog URI>
    dct:publisher <http://www.gbif.org/publisher/1cd669d0-80ea-11de-a9d0-f1765f95f18b#Organization>

<some dataset URI>
    dct:publisher <http://www.gbif.org/publisher/1cd669d0-80ea-11de-a9d0-f1765f95f18b#Organization>

<http://www.gbif.org/publisher/1cd669d0-80ea-11de-a9d0-f1765f95f18b#Organization>
    a foaf:Agent;
    foaf:name "Research Institute for Nature and Forest (INBO)"
```

All the information above is available within the IPT.

**Comment by peterdesmet** [comment]
Assigning to @simon-vc to implement this.

**Comment by peterdesmet** [comment]
As suggested by @pietercolpaert, I'm adding a `#Organization` to the URIs above.
